# Generated by Django 5.1 on 2024-08-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='restaurent_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('MX', 'Mexican'), ('GR', 'Greek'), ('AM', 'American'), ('OT', 'Others')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
