# Generated by Django 5.1 on 2024-08-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
