# Generated by Django 5.1 on 2024-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rating_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='capacity',
        ),
        migrations.AddField(
            model_name='restaurent',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
